export const AuctionsList = [
    {
        starts: "Starts Later",
        image: "/assets/house1.jpg",
        imageAlt: "Modern House Image",
        name: "4-Bedroom Modern House",
        price: 3000000,
        type: "House",
    },
    {
        starts: "Live",
        image: "/assets/electronics1.jpg",
        imageAlt: "Smart TV Image",
        name: "55-inch 4K Smart TV",
        price: 15000,
        type: "Electronics",
    },
    {
        starts: "Live",
        image: "/assets/arts1.jpg",
        imageAlt: "Painting Image",
        name: "Abstract Painting",
        price: 8000,
        type: "Arts",
    },
    {
        starts: "Starts Later",
        image: "/assets/industrial1.png",
        imageAlt: "Tractor Image",
        name: "Agricultural Tractor",
        price: 500000,
        type: "Industrial",
    },
    {
        starts: "Starts Later",
        image: "/assets/fashion1.webp",
        imageAlt: "Designer Dress Image",
        name: "Designer Evening Dress",
        price: 2500,
        type: "Fashion",
    },
    {
        starts: "Starts Later",
        image: "/assets/furniture1.jpg",
        imageAlt: "Sofa Set Image",
        name: "Luxury Sofa Set",
        price: 20000,
        type: "Furniture",
    },
    {
        starts: "Live",
        image: "/assets/vehicle1.jpg",
        imageAlt: "Car Image",
        name: "Toyota Corolla 2018",
        price: 650000,
        type: "Vehicle",
    },
    {
        starts: "Starts Later",
        image: "/assets/electronics2.jpg",
        imageAlt: "Laptop Image",
        name: "Gaming Laptop",
        price: 30000,
        type: "Electronics",
    },
    {
        starts: "Starts Later",
        image: "/assets/fashion2.webp",
        imageAlt: "Wristwatch Image",
        name: "Luxury Wristwatch",
        price: 5000,
        type: "Fashion",
    },
    {
        starts: "Live",
        image: "/assets/house2.jpg",
        imageAlt: "Villa Image",
        name: "Beachside Villa",
        price: 5000000,
        type: "House",
    },
    {
        starts: "Starts Later",
        image: "/assets/vehicle2.jpg",
        imageAlt: "Ford Image",
        name: "Ford",
        price: 350000,
        type: "Vehicle",
    }
];
